name: "Org1"
version: "1.0"

client:
  organization: Org1MSP
  credentialStore:
    path: ./.hfc-org1
    cryptoStore:
      path: ./.hfc-org1

organizations:
  Org1MSP:
    mspid: Org1MSP
    certificateAuthorities:
      - ca.org1.example.com
    adminPrivateKey:
      path: ../convector-tool-dev-env/network-objects/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/69c76b7cf25d590da9e1cc74f5c9de2414108226a79e2a81d31a8090435e613f_sk
    signedCert:
      path: ../convector-tool-dev-env/network-objects/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem

orderers:
  orderer.example.com:
    url: grpc://orderer.example.com:7050
    grpcOptions:
      ssl-target-name-override: orderer.example.com
      grpc-max-send-message-length: 15
    tlsCACerts:
      path: ../convector-tool-dev-env/network-objects/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem

certificateAuthorities:
  ca.org1.example.com:
    url: http://ca.org1.example.com:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: ../convector-tool-dev-env/network-objects/crypto-config/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    caName: ca.org1.example.com
