name: "Org2"
version: "1.0"

client:
  organization: Org2MSP
  credentialStore:
    path: ./.hfc-org2
    cryptoStore:
      path: ./.hfc-org2

organizations:
  Org2MSP:
    mspid: Org2MSP
    certificateAuthorities:
      - ca.org2.example.com
    adminPrivateKey:
      path: ../convector-tool-dev-env/network-objects/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/70d9a64cccff14248b04c5c77f39e965f9b0013dabb7311cc765ec82124c79fa_sk
    signedCert:
      path: ../convector-tool-dev-env/network-objects/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/Admin@org2.example.com-cert.pem

orderers:
  orderer.example.com:
    url: grpc://orderer.example.com:7050
    grpcOptions:
      ssl-target-name-override: orderer.example.com
      grpc-max-send-message-length: 15
    tlsCACerts:
      path: ../convector-tool-dev-env/network-objects/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem

certificateAuthorities:
  ca.org2.example.com:
    url: http://ca.org2.example.com:8054
    httpOptions:
      verify: false
    tlsCACerts:
      path: ../convector-tool-dev-env/network-objects/crypto-config/peerOrganizations/org2.example.com/ca/ca.org2.example.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    caName: ca.org2.example.com
